export declare const config: import("@tamagui/core").TamaguiInternalConfig<{
    color: {
        outline: import("@tamagui/core").Variable<string>;
        shadow: import("@tamagui/core").Variable<string>;
        primary: import("@tamagui/core").Variable<string>;
        secondary: import("@tamagui/core").Variable<string>;
        surfaceTint: import("@tamagui/core").Variable<string>;
        onPrimary: import("@tamagui/core").Variable<string>;
        primaryContainer: import("@tamagui/core").Variable<string>;
        onPrimaryContainer: import("@tamagui/core").Variable<string>;
        onSecondary: import("@tamagui/core").Variable<string>;
        secondaryContainer: import("@tamagui/core").Variable<string>;
        onSecondaryContainer: import("@tamagui/core").Variable<string>;
        tertiary: import("@tamagui/core").Variable<string>;
        onTertiary: import("@tamagui/core").Variable<string>;
        tertiaryContainer: import("@tamagui/core").Variable<string>;
        onTertiaryContainer: import("@tamagui/core").Variable<string>;
        error: import("@tamagui/core").Variable<string>;
        onError: import("@tamagui/core").Variable<string>;
        errorContainer: import("@tamagui/core").Variable<string>;
        onErrorContainer: import("@tamagui/core").Variable<string>;
        background: import("@tamagui/core").Variable<string>;
        onBackground: import("@tamagui/core").Variable<string>;
        surface: import("@tamagui/core").Variable<string>;
        onSurface: import("@tamagui/core").Variable<string>;
        onSurfaceOpacity: import("@tamagui/core").Variable<string>;
        surfaceVariant: import("@tamagui/core").Variable<string>;
        onSurfaceVariant: import("@tamagui/core").Variable<string>;
        outlineVariant: import("@tamagui/core").Variable<string>;
        shadow_opacity: import("@tamagui/core").Variable<string>;
        scrim: import("@tamagui/core").Variable<string>;
        inverseSurface: import("@tamagui/core").Variable<string>;
        inverseOnSurface: import("@tamagui/core").Variable<string>;
        inversePrimary: import("@tamagui/core").Variable<string>;
        primaryFixed: import("@tamagui/core").Variable<string>;
        onPrimaryFixed: import("@tamagui/core").Variable<string>;
        primaryFixedDim: import("@tamagui/core").Variable<string>;
        onPrimaryFixedVariant: import("@tamagui/core").Variable<string>;
        secondaryFixed: import("@tamagui/core").Variable<string>;
        onSecondaryFixed: import("@tamagui/core").Variable<string>;
        secondaryFixedDim: import("@tamagui/core").Variable<string>;
        onSecondaryFixedVariant: import("@tamagui/core").Variable<string>;
        tertiaryFixed: import("@tamagui/core").Variable<string>;
        onTertiaryFixed: import("@tamagui/core").Variable<string>;
        tertiaryFixedDim: import("@tamagui/core").Variable<string>;
        onTertiaryFixedVariant: import("@tamagui/core").Variable<string>;
        surfaceDim: import("@tamagui/core").Variable<string>;
        surfaceBright: import("@tamagui/core").Variable<string>;
        surfaceContainerLowest: import("@tamagui/core").Variable<string>;
        surfaceContainerLow: import("@tamagui/core").Variable<string>;
        surfaceContainer: import("@tamagui/core").Variable<string>;
        surfaceContainerHigh: import("@tamagui/core").Variable<string>;
        surfaceContainerHighest: import("@tamagui/core").Variable<string>;
        warning: import("@tamagui/core").Variable<string>;
        onWarning: import("@tamagui/core").Variable<string>;
        warningContainer: import("@tamagui/core").Variable<string>;
        onWarningContainer: import("@tamagui/core").Variable<string>;
        success: import("@tamagui/core").Variable<string>;
        onSuccess: import("@tamagui/core").Variable<string>;
        successContainer: import("@tamagui/core").Variable<string>;
        onSuccessContainer: import("@tamagui/core").Variable<string>;
        info: import("@tamagui/core").Variable<string>;
        onInfo: import("@tamagui/core").Variable<string>;
        infoContainer: import("@tamagui/core").Variable<string>;
        onInfoContainer: import("@tamagui/core").Variable<string>;
        yellow1Light: import("@tamagui/core").Variable<string>;
        yellow2Light: import("@tamagui/core").Variable<string>;
        yellow3Light: import("@tamagui/core").Variable<string>;
        yellow4Light: import("@tamagui/core").Variable<string>;
        yellow5Light: import("@tamagui/core").Variable<string>;
        yellow6Light: import("@tamagui/core").Variable<string>;
        yellow7Light: import("@tamagui/core").Variable<string>;
        yellow8Light: import("@tamagui/core").Variable<string>;
        yellow9Light: import("@tamagui/core").Variable<string>;
        yellow10Light: import("@tamagui/core").Variable<string>;
        yellow11Light: import("@tamagui/core").Variable<string>;
        yellow12Light: import("@tamagui/core").Variable<string>;
        red1Light: import("@tamagui/core").Variable<string>;
        red2Light: import("@tamagui/core").Variable<string>;
        red3Light: import("@tamagui/core").Variable<string>;
        red4Light: import("@tamagui/core").Variable<string>;
        red5Light: import("@tamagui/core").Variable<string>;
        red6Light: import("@tamagui/core").Variable<string>;
        red7Light: import("@tamagui/core").Variable<string>;
        red8Light: import("@tamagui/core").Variable<string>;
        red9Light: import("@tamagui/core").Variable<string>;
        red10Light: import("@tamagui/core").Variable<string>;
        red11Light: import("@tamagui/core").Variable<string>;
        red12Light: import("@tamagui/core").Variable<string>;
        purple1Light: import("@tamagui/core").Variable<string>;
        purple2Light: import("@tamagui/core").Variable<string>;
        purple3Light: import("@tamagui/core").Variable<string>;
        purple4Light: import("@tamagui/core").Variable<string>;
        purple5Light: import("@tamagui/core").Variable<string>;
        purple6Light: import("@tamagui/core").Variable<string>;
        purple7Light: import("@tamagui/core").Variable<string>;
        purple8Light: import("@tamagui/core").Variable<string>;
        purple9Light: import("@tamagui/core").Variable<string>;
        purple10Light: import("@tamagui/core").Variable<string>;
        purple11Light: import("@tamagui/core").Variable<string>;
        purple12Light: import("@tamagui/core").Variable<string>;
        pink1Light: import("@tamagui/core").Variable<string>;
        pink2Light: import("@tamagui/core").Variable<string>;
        pink3Light: import("@tamagui/core").Variable<string>;
        pink4Light: import("@tamagui/core").Variable<string>;
        pink5Light: import("@tamagui/core").Variable<string>;
        pink6Light: import("@tamagui/core").Variable<string>;
        pink7Light: import("@tamagui/core").Variable<string>;
        pink8Light: import("@tamagui/core").Variable<string>;
        pink9Light: import("@tamagui/core").Variable<string>;
        pink10Light: import("@tamagui/core").Variable<string>;
        pink11Light: import("@tamagui/core").Variable<string>;
        pink12Light: import("@tamagui/core").Variable<string>;
        orange1Light: import("@tamagui/core").Variable<string>;
        orange2Light: import("@tamagui/core").Variable<string>;
        orange3Light: import("@tamagui/core").Variable<string>;
        orange4Light: import("@tamagui/core").Variable<string>;
        orange5Light: import("@tamagui/core").Variable<string>;
        orange6Light: import("@tamagui/core").Variable<string>;
        orange7Light: import("@tamagui/core").Variable<string>;
        orange8Light: import("@tamagui/core").Variable<string>;
        orange9Light: import("@tamagui/core").Variable<string>;
        orange10Light: import("@tamagui/core").Variable<string>;
        orange11Light: import("@tamagui/core").Variable<string>;
        orange12Light: import("@tamagui/core").Variable<string>;
        green1Light: import("@tamagui/core").Variable<string>;
        green2Light: import("@tamagui/core").Variable<string>;
        green3Light: import("@tamagui/core").Variable<string>;
        green4Light: import("@tamagui/core").Variable<string>;
        green5Light: import("@tamagui/core").Variable<string>;
        green6Light: import("@tamagui/core").Variable<string>;
        green7Light: import("@tamagui/core").Variable<string>;
        green8Light: import("@tamagui/core").Variable<string>;
        green9Light: import("@tamagui/core").Variable<string>;
        green10Light: import("@tamagui/core").Variable<string>;
        green11Light: import("@tamagui/core").Variable<string>;
        green12Light: import("@tamagui/core").Variable<string>;
        gray1Light: import("@tamagui/core").Variable<string>;
        gray2Light: import("@tamagui/core").Variable<string>;
        gray3Light: import("@tamagui/core").Variable<string>;
        gray4Light: import("@tamagui/core").Variable<string>;
        gray5Light: import("@tamagui/core").Variable<string>;
        gray6Light: import("@tamagui/core").Variable<string>;
        gray7Light: import("@tamagui/core").Variable<string>;
        gray8Light: import("@tamagui/core").Variable<string>;
        gray9Light: import("@tamagui/core").Variable<string>;
        gray10Light: import("@tamagui/core").Variable<string>;
        gray11Light: import("@tamagui/core").Variable<string>;
        gray12Light: import("@tamagui/core").Variable<string>;
        blue1Light: import("@tamagui/core").Variable<string>;
        blue2Light: import("@tamagui/core").Variable<string>;
        blue3Light: import("@tamagui/core").Variable<string>;
        blue4Light: import("@tamagui/core").Variable<string>;
        blue5Light: import("@tamagui/core").Variable<string>;
        blue6Light: import("@tamagui/core").Variable<string>;
        blue7Light: import("@tamagui/core").Variable<string>;
        blue8Light: import("@tamagui/core").Variable<string>;
        blue9Light: import("@tamagui/core").Variable<string>;
        blue10Light: import("@tamagui/core").Variable<string>;
        blue11Light: import("@tamagui/core").Variable<string>;
        blue12Light: import("@tamagui/core").Variable<string>;
        yellow1Dark: import("@tamagui/core").Variable<string>;
        yellow2Dark: import("@tamagui/core").Variable<string>;
        yellow3Dark: import("@tamagui/core").Variable<string>;
        yellow4Dark: import("@tamagui/core").Variable<string>;
        yellow5Dark: import("@tamagui/core").Variable<string>;
        yellow6Dark: import("@tamagui/core").Variable<string>;
        yellow7Dark: import("@tamagui/core").Variable<string>;
        yellow8Dark: import("@tamagui/core").Variable<string>;
        yellow9Dark: import("@tamagui/core").Variable<string>;
        yellow10Dark: import("@tamagui/core").Variable<string>;
        yellow11Dark: import("@tamagui/core").Variable<string>;
        yellow12Dark: import("@tamagui/core").Variable<string>;
        red1Dark: import("@tamagui/core").Variable<string>;
        red2Dark: import("@tamagui/core").Variable<string>;
        red3Dark: import("@tamagui/core").Variable<string>;
        red4Dark: import("@tamagui/core").Variable<string>;
        red5Dark: import("@tamagui/core").Variable<string>;
        red6Dark: import("@tamagui/core").Variable<string>;
        red7Dark: import("@tamagui/core").Variable<string>;
        red8Dark: import("@tamagui/core").Variable<string>;
        red9Dark: import("@tamagui/core").Variable<string>;
        red10Dark: import("@tamagui/core").Variable<string>;
        red11Dark: import("@tamagui/core").Variable<string>;
        red12Dark: import("@tamagui/core").Variable<string>;
        purple1Dark: import("@tamagui/core").Variable<string>;
        purple2Dark: import("@tamagui/core").Variable<string>;
        purple3Dark: import("@tamagui/core").Variable<string>;
        purple4Dark: import("@tamagui/core").Variable<string>;
        purple5Dark: import("@tamagui/core").Variable<string>;
        purple6Dark: import("@tamagui/core").Variable<string>;
        purple7Dark: import("@tamagui/core").Variable<string>;
        purple8Dark: import("@tamagui/core").Variable<string>;
        purple9Dark: import("@tamagui/core").Variable<string>;
        purple10Dark: import("@tamagui/core").Variable<string>;
        purple11Dark: import("@tamagui/core").Variable<string>;
        purple12Dark: import("@tamagui/core").Variable<string>;
        pink1Dark: import("@tamagui/core").Variable<string>;
        pink2Dark: import("@tamagui/core").Variable<string>;
        pink3Dark: import("@tamagui/core").Variable<string>;
        pink4Dark: import("@tamagui/core").Variable<string>;
        pink5Dark: import("@tamagui/core").Variable<string>;
        pink6Dark: import("@tamagui/core").Variable<string>;
        pink7Dark: import("@tamagui/core").Variable<string>;
        pink8Dark: import("@tamagui/core").Variable<string>;
        pink9Dark: import("@tamagui/core").Variable<string>;
        pink10Dark: import("@tamagui/core").Variable<string>;
        pink11Dark: import("@tamagui/core").Variable<string>;
        pink12Dark: import("@tamagui/core").Variable<string>;
        orange1Dark: import("@tamagui/core").Variable<string>;
        orange2Dark: import("@tamagui/core").Variable<string>;
        orange3Dark: import("@tamagui/core").Variable<string>;
        orange4Dark: import("@tamagui/core").Variable<string>;
        orange5Dark: import("@tamagui/core").Variable<string>;
        orange6Dark: import("@tamagui/core").Variable<string>;
        orange7Dark: import("@tamagui/core").Variable<string>;
        orange8Dark: import("@tamagui/core").Variable<string>;
        orange9Dark: import("@tamagui/core").Variable<string>;
        orange10Dark: import("@tamagui/core").Variable<string>;
        orange11Dark: import("@tamagui/core").Variable<string>;
        orange12Dark: import("@tamagui/core").Variable<string>;
        green1Dark: import("@tamagui/core").Variable<string>;
        green2Dark: import("@tamagui/core").Variable<string>;
        green3Dark: import("@tamagui/core").Variable<string>;
        green4Dark: import("@tamagui/core").Variable<string>;
        green5Dark: import("@tamagui/core").Variable<string>;
        green6Dark: import("@tamagui/core").Variable<string>;
        green7Dark: import("@tamagui/core").Variable<string>;
        green8Dark: import("@tamagui/core").Variable<string>;
        green9Dark: import("@tamagui/core").Variable<string>;
        green10Dark: import("@tamagui/core").Variable<string>;
        green11Dark: import("@tamagui/core").Variable<string>;
        green12Dark: import("@tamagui/core").Variable<string>;
        gray1Dark: import("@tamagui/core").Variable<string>;
        gray2Dark: import("@tamagui/core").Variable<string>;
        gray3Dark: import("@tamagui/core").Variable<string>;
        gray4Dark: import("@tamagui/core").Variable<string>;
        gray5Dark: import("@tamagui/core").Variable<string>;
        gray6Dark: import("@tamagui/core").Variable<string>;
        gray7Dark: import("@tamagui/core").Variable<string>;
        gray8Dark: import("@tamagui/core").Variable<string>;
        gray9Dark: import("@tamagui/core").Variable<string>;
        gray10Dark: import("@tamagui/core").Variable<string>;
        gray11Dark: import("@tamagui/core").Variable<string>;
        gray12Dark: import("@tamagui/core").Variable<string>;
        blue1Dark: import("@tamagui/core").Variable<string>;
        blue2Dark: import("@tamagui/core").Variable<string>;
        blue3Dark: import("@tamagui/core").Variable<string>;
        blue4Dark: import("@tamagui/core").Variable<string>;
        blue5Dark: import("@tamagui/core").Variable<string>;
        blue6Dark: import("@tamagui/core").Variable<string>;
        blue7Dark: import("@tamagui/core").Variable<string>;
        blue8Dark: import("@tamagui/core").Variable<string>;
        blue9Dark: import("@tamagui/core").Variable<string>;
        blue10Dark: import("@tamagui/core").Variable<string>;
        blue11Dark: import("@tamagui/core").Variable<string>;
        blue12Dark: import("@tamagui/core").Variable<string>;
    };
    space: {
        $0: import("@tamagui/core").Variable<number>;
        "$0.25": import("@tamagui/core").Variable<number>;
        "$0.5": import("@tamagui/core").Variable<number>;
        "$0.75": import("@tamagui/core").Variable<number>;
        $1: import("@tamagui/core").Variable<number>;
        "$1.5": import("@tamagui/core").Variable<number>;
        $2: import("@tamagui/core").Variable<number>;
        "$2.5": import("@tamagui/core").Variable<number>;
        $3: import("@tamagui/core").Variable<number>;
        "$3.5": import("@tamagui/core").Variable<number>;
        $4: import("@tamagui/core").Variable<number>;
        $true: import("@tamagui/core").Variable<number>;
        "$4.5": import("@tamagui/core").Variable<number>;
        $5: import("@tamagui/core").Variable<number>;
        $6: import("@tamagui/core").Variable<number>;
        $7: import("@tamagui/core").Variable<number>;
        $8: import("@tamagui/core").Variable<number>;
        $9: import("@tamagui/core").Variable<number>;
        $10: import("@tamagui/core").Variable<number>;
        $11: import("@tamagui/core").Variable<number>;
        $12: import("@tamagui/core").Variable<number>;
        $13: import("@tamagui/core").Variable<number>;
        $14: import("@tamagui/core").Variable<number>;
        $15: import("@tamagui/core").Variable<number>;
        $16: import("@tamagui/core").Variable<number>;
        $17: import("@tamagui/core").Variable<number>;
        $18: import("@tamagui/core").Variable<number>;
        $19: import("@tamagui/core").Variable<number>;
        $20: import("@tamagui/core").Variable<number>;
        "$-0.25": import("@tamagui/core").Variable<number>;
        "$-0.5": import("@tamagui/core").Variable<number>;
        "$-0.75": import("@tamagui/core").Variable<number>;
        "$-1": import("@tamagui/core").Variable<number>;
        "$-1.5": import("@tamagui/core").Variable<number>;
        "$-2": import("@tamagui/core").Variable<number>;
        "$-2.5": import("@tamagui/core").Variable<number>;
        "$-3": import("@tamagui/core").Variable<number>;
        "$-3.5": import("@tamagui/core").Variable<number>;
        "$-4": import("@tamagui/core").Variable<number>;
        "$-true": import("@tamagui/core").Variable<number>;
        "$-4.5": import("@tamagui/core").Variable<number>;
        "$-5": import("@tamagui/core").Variable<number>;
        "$-6": import("@tamagui/core").Variable<number>;
        "$-7": import("@tamagui/core").Variable<number>;
        "$-8": import("@tamagui/core").Variable<number>;
        "$-9": import("@tamagui/core").Variable<number>;
        "$-10": import("@tamagui/core").Variable<number>;
        "$-11": import("@tamagui/core").Variable<number>;
        "$-12": import("@tamagui/core").Variable<number>;
        "$-13": import("@tamagui/core").Variable<number>;
        "$-14": import("@tamagui/core").Variable<number>;
        "$-15": import("@tamagui/core").Variable<number>;
        "$-16": import("@tamagui/core").Variable<number>;
        "$-17": import("@tamagui/core").Variable<number>;
        "$-18": import("@tamagui/core").Variable<number>;
        "$-19": import("@tamagui/core").Variable<number>;
        "$-20": import("@tamagui/core").Variable<number>;
    };
    size: {
        list_item_height: import("@tamagui/core").Variable<number>;
        nav_rail_width: import("@tamagui/core").Variable<number>;
        main_max_width: import("@tamagui/core").Variable<number>;
        pane_supporting: import("@tamagui/core").Variable<number>;
        $0: import("@tamagui/core").Variable<number>;
        "$0.25": import("@tamagui/core").Variable<number>;
        "$0.5": import("@tamagui/core").Variable<number>;
        "$0.75": import("@tamagui/core").Variable<number>;
        $1: import("@tamagui/core").Variable<number>;
        "$1.5": import("@tamagui/core").Variable<number>;
        $2: import("@tamagui/core").Variable<number>;
        "$2.5": import("@tamagui/core").Variable<number>;
        $3: import("@tamagui/core").Variable<number>;
        "$3.5": import("@tamagui/core").Variable<number>;
        $4: import("@tamagui/core").Variable<number>;
        $true: import("@tamagui/core").Variable<number>;
        "$4.5": import("@tamagui/core").Variable<number>;
        $5: import("@tamagui/core").Variable<number>;
        $6: import("@tamagui/core").Variable<number>;
        $7: import("@tamagui/core").Variable<number>;
        $8: import("@tamagui/core").Variable<number>;
        $9: import("@tamagui/core").Variable<number>;
        $10: import("@tamagui/core").Variable<number>;
        $11: import("@tamagui/core").Variable<number>;
        $12: import("@tamagui/core").Variable<number>;
        $13: import("@tamagui/core").Variable<number>;
        $14: import("@tamagui/core").Variable<number>;
        $15: import("@tamagui/core").Variable<number>;
        $16: import("@tamagui/core").Variable<number>;
        $17: import("@tamagui/core").Variable<number>;
        $18: import("@tamagui/core").Variable<number>;
        $19: import("@tamagui/core").Variable<number>;
        $20: import("@tamagui/core").Variable<number>;
    };
    radius: {
        0: import("@tamagui/core").Variable<number>;
        9: import("@tamagui/core").Variable<number>;
        1: import("@tamagui/core").Variable<number>;
        10: import("@tamagui/core").Variable<number>;
        11: import("@tamagui/core").Variable<number>;
        12: import("@tamagui/core").Variable<number>;
        2: import("@tamagui/core").Variable<number>;
        true: import("@tamagui/core").Variable<number>;
        4: import("@tamagui/core").Variable<number>;
        8: import("@tamagui/core").Variable<number>;
        6: import("@tamagui/core").Variable<number>;
        3: import("@tamagui/core").Variable<number>;
        5: import("@tamagui/core").Variable<number>;
        7: import("@tamagui/core").Variable<number>;
    };
    zIndex: {
        0: import("@tamagui/core").Variable<number>;
        1: import("@tamagui/core").Variable<number>;
        5: import("@tamagui/core").Variable<number>;
        4: import("@tamagui/core").Variable<number>;
        3: import("@tamagui/core").Variable<number>;
        2: import("@tamagui/core").Variable<number>;
    };
} & Omit<{
    border: {
        outline: import("@tamagui/core").Variable<number>;
        divider_width: import("@tamagui/core").Variable<number>;
        true: import("@tamagui/core").Variable<number>;
    };
    shape: {
        corner_extra_small: import("@tamagui/core").Variable<string | number>;
        corner_full: import("@tamagui/core").Variable<string | number>;
        corner_l: import("@tamagui/core").Variable<string | number>;
        corner_large: import("@tamagui/core").Variable<string | number>;
        corner_m: import("@tamagui/core").Variable<string | number>;
        corner_medium: import("@tamagui/core").Variable<string | number>;
        corner_none: import("@tamagui/core").Variable<string | number>;
        corner_sm: import("@tamagui/core").Variable<string | number>;
        corner_small: import("@tamagui/core").Variable<string | number>;
        corner_xl: import("@tamagui/core").Variable<string | number>;
        corner_xs: import("@tamagui/core").Variable<string | number>;
        bs_1: import("@tamagui/core").Variable<string | number>;
    };
    shadow: {
        0: import("@tamagui/core").Variable<string | number>;
        2: import("@tamagui/core").Variable<string | number>;
        1: import("@tamagui/core").Variable<string | number>;
        true: import("@tamagui/core").Variable<string | number>;
        4: import("@tamagui/core").Variable<string | number>;
        bs_1: import("@tamagui/core").Variable<string | number>;
        3: import("@tamagui/core").Variable<string | number>;
        5: import("@tamagui/core").Variable<string | number>;
    };
    color: {
        outline: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        shadow: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        primary: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        secondary: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        surfaceTint: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onPrimary: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        primaryContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onPrimaryContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onSecondary: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        secondaryContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onSecondaryContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        tertiary: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onTertiary: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        tertiaryContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onTertiaryContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        error: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onError: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        errorContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onErrorContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        background: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onBackground: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        surface: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onSurface: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onSurfaceOpacity: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        surfaceVariant: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onSurfaceVariant: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        outlineVariant: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        shadow_opacity: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        scrim: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        inverseSurface: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        inverseOnSurface: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        inversePrimary: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        primaryFixed: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onPrimaryFixed: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        primaryFixedDim: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onPrimaryFixedVariant: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        secondaryFixed: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onSecondaryFixed: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        secondaryFixedDim: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onSecondaryFixedVariant: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        tertiaryFixed: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onTertiaryFixed: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        tertiaryFixedDim: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onTertiaryFixedVariant: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        surfaceDim: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        surfaceBright: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        surfaceContainerLowest: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        surfaceContainerLow: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        surfaceContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        surfaceContainerHigh: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        surfaceContainerHighest: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        warning: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onWarning: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        warningContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onWarningContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        success: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onSuccess: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        successContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onSuccessContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        info: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onInfo: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        infoContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        onInfoContainer: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow1Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow2Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow3Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow4Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow5Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow6Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow7Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow8Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow9Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow10Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow11Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow12Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red1Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red2Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red3Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red4Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red5Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red6Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red7Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red8Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red9Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red10Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red11Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red12Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple1Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple2Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple3Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple4Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple5Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple6Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple7Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple8Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple9Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple10Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple11Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple12Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink1Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink2Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink3Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink4Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink5Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink6Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink7Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink8Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink9Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink10Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink11Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink12Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange1Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange2Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange3Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange4Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange5Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange6Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange7Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange8Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange9Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange10Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange11Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange12Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green1Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green2Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green3Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green4Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green5Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green6Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green7Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green8Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green9Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green10Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green11Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green12Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray1Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray2Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray3Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray4Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray5Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray6Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray7Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray8Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray9Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray10Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray11Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray12Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue1Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue2Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue3Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue4Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue5Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue6Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue7Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue8Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue9Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue10Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue11Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue12Light: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow1Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow2Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow3Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow4Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow5Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow6Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow7Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow8Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow9Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow10Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow11Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        yellow12Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red1Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red2Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red3Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red4Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red5Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red6Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red7Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red8Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red9Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red10Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red11Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        red12Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple1Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple2Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple3Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple4Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple5Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple6Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple7Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple8Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple9Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple10Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple11Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        purple12Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink1Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink2Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink3Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink4Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink5Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink6Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink7Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink8Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink9Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink10Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink11Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        pink12Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange1Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange2Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange3Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange4Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange5Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange6Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange7Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange8Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange9Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange10Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange11Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        orange12Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green1Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green2Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green3Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green4Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green5Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green6Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green7Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green8Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green9Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green10Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green11Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        green12Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray1Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray2Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray3Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray4Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray5Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray6Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray7Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray8Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray9Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray10Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray11Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        gray12Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue1Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue2Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue3Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue4Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue5Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue6Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue7Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue8Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue9Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue10Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue11Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
        blue12Dark: import("@tamagui/core").Variable<string | import("@tamagui/core").Variable<string>>;
    };
    spacing: {
        margin_compact: import("@tamagui/core").Variable<number>;
        form_gap: import("@tamagui/core").Variable<number>;
        card_gap: import("@tamagui/core").Variable<number>;
        compact_margin: import("@tamagui/core").Variable<number>;
        medium_margin: import("@tamagui/core").Variable<number>;
        exp_margin: import("@tamagui/core").Variable<number>;
        large_margin: import("@tamagui/core").Variable<number>;
        card_body: import("@tamagui/core").Variable<number>;
        card_body_1: import("@tamagui/core").Variable<number>;
        card_body_2: import("@tamagui/core").Variable<number>;
        card_body_3: import("@tamagui/core").Variable<number>;
        chip_spacing: import("@tamagui/core").Variable<number>;
        fab_padding: import("@tamagui/core").Variable<number>;
        pane_gap: import("@tamagui/core").Variable<number>;
    };
    size: {
        list_item_height: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        nav_rail_width: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        main_max_width: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        pane_supporting: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $0: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        "$0.25": import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        "$0.5": import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        "$0.75": import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $1: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        "$1.5": import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $2: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        "$2.5": import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $3: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        "$3.5": import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $4: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $true: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        "$4.5": import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $5: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $6: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $7: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $8: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $9: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $10: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $11: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $12: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $13: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $14: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $15: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $16: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $17: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $18: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $19: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
        $20: import("@tamagui/core").Variable<number | import("@tamagui/core").Variable<number>>;
    };
    gmp: {
        true: import("@tamagui/core").Variable<string>;
        auburn: import("@tamagui/core").Variable<string>;
        onAuburn: import("@tamagui/core").Variable<string>;
        red: import("@tamagui/core").Variable<string>;
        pink: import("@tamagui/core").Variable<string>;
        onPink: import("@tamagui/core").Variable<string>;
        orange: import("@tamagui/core").Variable<string>;
        onOrange: import("@tamagui/core").Variable<string>;
        cream: import("@tamagui/core").Variable<string>;
        onCream: import("@tamagui/core").Variable<string>;
        gold: import("@tamagui/core").Variable<string>;
    };
    provenance: {
        primary: import("@tamagui/core").Variable<string>;
        primaryAlt: import("@tamagui/core").Variable<string>;
        secondary: import("@tamagui/core").Variable<string>;
        secondaryAlt: import("@tamagui/core").Variable<string>;
        secondaryAlt2: import("@tamagui/core").Variable<string>;
    };
    space: {
        $0: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$0.25": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$0.5": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$0.75": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $1: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$1.5": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $2: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$2.5": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $3: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$3.5": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $4: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $true: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$4.5": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $5: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $6: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $7: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $8: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $9: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $10: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $11: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $12: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $13: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $14: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $15: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $16: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $17: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $18: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $19: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        $20: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-0.25": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-0.5": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-0.75": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-1": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-1.5": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-2": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-2.5": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-3": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-3.5": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-4": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-true": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-4.5": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-5": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-6": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-7": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-8": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-9": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-10": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-11": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-12": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-13": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-14": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-15": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-16": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-17": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-18": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-19": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        "$-20": import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
    };
    radius: {
        0: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        9: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        1: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        10: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        11: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        12: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        2: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        true: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        4: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        8: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        6: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        3: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        5: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        7: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
    };
    zIndex: {
        0: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        1: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        5: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        4: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        3: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
        2: import("@tamagui/core").Variable<import("@tamagui/core").Variable<number>>;
    };
}, "size" | "color" | "space" | "radius" | "zIndex">, {
    dark: {
        primary: string;
        surfaceTint: string;
        onPrimary: string;
        primaryContainer: string;
        onPrimaryContainer: string;
        secondary: string;
        onSecondary: string;
        secondaryContainer: string;
        onSecondaryContainer: string;
        tertiary: string;
        onTertiary: string;
        tertiaryContainer: string;
        onTertiaryContainer: string;
        error: string;
        onError: string;
        errorContainer: string;
        onErrorContainer: string;
        background: string;
        onBackground: string;
        surface: string;
        onSurface: string;
        surfaceVariant: string;
        onSurfaceVariant: string;
        outline: string;
        outlineVariant: string;
        shadow: string;
        scrim: string;
        inverseSurface: string;
        inverseOnSurface: string;
        inversePrimary: string;
        primaryFixed: string;
        onPrimaryFixed: string;
        primaryFixedDim: string;
        onPrimaryFixedVariant: string;
        secondaryFixed: string;
        onSecondaryFixed: string;
        secondaryFixedDim: string;
        onSecondaryFixedVariant: string;
        tertiaryFixed: string;
        onTertiaryFixed: string;
        tertiaryFixedDim: string;
        onTertiaryFixedVariant: string;
        surfaceDim: string;
        surfaceBright: string;
        surfaceContainerLowest: string;
        surfaceContainerLow: string;
        surfaceContainer: string;
        surfaceContainerHigh: string;
        surfaceContainerHighest: string;
    };
    light: {
        primary: string;
        surfaceTint: string;
        onPrimary: string;
        primaryContainer: string;
        onPrimaryContainer: string;
        secondary: string;
        onSecondary: string;
        secondaryContainer: string;
        onSecondaryContainer: string;
        tertiary: string;
        onTertiary: string;
        tertiaryContainer: string;
        onTertiaryContainer: string;
        error: string;
        onError: string;
        errorContainer: string;
        onErrorContainer: string;
        background: string;
        onBackground: string;
        surface: string;
        onSurface: string;
        surfaceVariant: string;
        onSurfaceVariant: string;
        outline: string;
        outlineVariant: string;
        shadow: string;
        scrim: string;
        inverseSurface: string;
        inverseOnSurface: string;
        inversePrimary: string;
        primaryFixed: string;
        onPrimaryFixed: string;
        primaryFixedDim: string;
        onPrimaryFixedVariant: string;
        secondaryFixed: string;
        onSecondaryFixed: string;
        secondaryFixedDim: string;
        onSecondaryFixedVariant: string;
        tertiaryFixed: string;
        onTertiaryFixed: string;
        tertiaryFixedDim: string;
        onTertiaryFixedVariant: string;
        surfaceDim: string;
        surfaceBright: string;
        surfaceContainerLowest: string;
        surfaceContainerLow: string;
        surfaceContainer: string;
        surfaceContainerHigh: string;
        surfaceContainerHighest: string;
    };
}, {
    readonly ussel: "userSelect";
    readonly cur: "cursor";
    readonly pe: "pointerEvents";
    readonly col: "color";
    readonly ff: "fontFamily";
    readonly fos: "fontSize";
    readonly fost: "fontStyle";
    readonly fow: "fontWeight";
    readonly ls: "letterSpacing";
    readonly lh: "lineHeight";
    readonly ta: "textAlign";
    readonly tt: "textTransform";
    readonly ww: "wordWrap";
    readonly ac: "alignContent";
    readonly ai: "alignItems";
    readonly als: "alignSelf";
    readonly b: "bottom";
    readonly bc: "backgroundColor";
    readonly bg: "backgroundColor";
    readonly bbc: "borderBottomColor";
    readonly bblr: "borderBottomLeftRadius";
    readonly bbrr: "borderBottomRightRadius";
    readonly bbw: "borderBottomWidth";
    readonly blc: "borderLeftColor";
    readonly blw: "borderLeftWidth";
    readonly boc: "borderColor";
    readonly br: "borderRadius";
    readonly bs: "borderStyle";
    readonly brw: "borderRightWidth";
    readonly brc: "borderRightColor";
    readonly btc: "borderTopColor";
    readonly btlr: "borderTopLeftRadius";
    readonly btrr: "borderTopRightRadius";
    readonly btw: "borderTopWidth";
    readonly bw: "borderWidth";
    readonly dsp: "display";
    readonly f: "flex";
    readonly fb: "flexBasis";
    readonly fd: "flexDirection";
    readonly fg: "flexGrow";
    readonly fs: "flexShrink";
    readonly fw: "flexWrap";
    readonly h: "height";
    readonly jc: "justifyContent";
    readonly l: "left";
    readonly m: "margin";
    readonly mah: "maxHeight";
    readonly maw: "maxWidth";
    readonly mb: "marginBottom";
    readonly mih: "minHeight";
    readonly miw: "minWidth";
    readonly ml: "marginLeft";
    readonly mr: "marginRight";
    readonly mt: "marginTop";
    readonly mx: "marginHorizontal";
    readonly my: "marginVertical";
    readonly o: "opacity";
    readonly ov: "overflow";
    readonly p: "padding";
    readonly pb: "paddingBottom";
    readonly pl: "paddingLeft";
    readonly pos: "position";
    readonly pr: "paddingRight";
    readonly pt: "paddingTop";
    readonly px: "paddingHorizontal";
    readonly py: "paddingVertical";
    readonly r: "right";
    readonly shac: "shadowColor";
    readonly shar: "shadowRadius";
    readonly shof: "shadowOffset";
    readonly shop: "shadowOpacity";
    readonly t: "top";
    readonly w: "width";
    readonly zi: "zIndex";
}, {
    hoverNone: {
        hover: string;
    };
    pointerCoarse: {
        pointer: string;
    };
    sm: {
        maxWidth: number;
    };
    compact: {
        maxWidth: number;
    };
    medium: {
        maxWidth: number;
    };
    expanded: {
        maxWidth: number;
    };
}, {
    "100ms": {
        type: "timing";
        duration: number;
    };
    "300ms": {
        type: "timing";
        duration: number;
    };
    bouncy: {
        damping: number;
        mass: number;
        stiffness: number;
    };
    lazy: {
        damping: number;
        stiffness: number;
    };
    medium: {
        damping: number;
        stiffness: number;
        mass: number;
    };
    slow: {
        damping: number;
        stiffness: number;
    };
    quick: {
        damping: number;
        mass: number;
        stiffness: number;
    };
    tooltip: {
        damping: number;
        mass: number;
        stiffness: number;
    };
}, {
    heading: any;
    body: any;
    serif: any;
}, {
    allowedStyleValues: "somewhat-strict";
}>;
export default config;
//# sourceMappingURL=tamagui.config.d.ts.map